######################################################################
# Automatically generated by qmake (2.01a) Mon 14. Feb 20:32:11 2011
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS=src
