######################################################################
# Automatically generated by qmake (2.01a) Mon 14. Feb 21:03:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += c:/Coding/QtQuarqd/src
INCLUDEPATH += .

# Input
HEADERS += ant.h \
           ant_channel.h \
           channel_manager.h \
           configuration.h \
           quarqd.h 
SOURCES += ant.c ant_channel.c channel_manager.c configuration.c main.c
